// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHYogcE_eePnTJHlaM__TvipucvYfW3tw',
    appId: '1:217173588974:android:db62088c4d7bf15dfd2cff',
    messagingSenderId: '217173588974',
    projectId: 'pos-account-32413',
    storageBucket: 'pos-account-32413.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFJHDMSfSoJ1uDtCoEE0duyn_pdNT5Qbw',
    appId: '1:217173588974:ios:3c092b7a093d82fffd2cff',
    messagingSenderId: '217173588974',
    projectId: 'pos-account-32413',
    storageBucket: 'pos-account-32413.appspot.com',
    iosClientId:
        '217173588974-ofltran6lnk952lj61h3bmja2k4f79ug.apps.googleusercontent.com',
    iosBundleId: 'com.volgai.posAccount',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFJHDMSfSoJ1uDtCoEE0duyn_pdNT5Qbw',
    appId: '1:217173588974:ios:3c092b7a093d82fffd2cff',
    messagingSenderId: '217173588974',
    projectId: 'pos-account-32413',
    storageBucket: 'pos-account-32413.appspot.com',
    iosClientId:
        '217173588974-ofltran6lnk952lj61h3bmja2k4f79ug.apps.googleusercontent.com',
    iosBundleId: 'com.volgai.posAccount',
  );
}
